version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: portfolio-app
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  portfolio-data: