import React from "react";
import Typewriter from "typewriter-effect";

function Type() {
    return (
        <Typewriter
            options={{
                strings: [
                    "Développeur",
                    "Blockchain quantique",
                    "Programmation",
                    "Synergologie",
                    "Web",
                    "Cloud",
                    "Véga Missyl",
                    "Numérique",
                    "JavaScript",
                    "Refactoring quantique",
                    "Full-Stack",
                    "Kubernetes",
                    "Stratégie biomimétique",
                    "Intelligence Artificielle",
                    "Web",
                    "Technologie",
                    "Code",
                    "Startup",
                    "Application",
                    "Conscience algorithmique",
                    "Back-End",
                    "NoSQL",
                    "Modélisation transcendantale",
                    "GitHub",
                    "Docker",
                    "API",
                    "Systématisation algorithmique",
                    "Big Data",
                    "Microservices",
                    "Nanotechnologie inversée",
                    "Front-End",
                    "Automatisation",
                    "Intelligence synthétique",
                    "Expansion ontologique",
                    "React",
                    "Testing",
                    "Computing neuro-évolutif",
                    "Serverless",
                    "Web3",
                    "Votre exter sait faire des créneaux en un seul coup",
                    "SQL",
                    "Symfony",
                    "Disruption exponentielle",
                    "UX/UI",
                    "Alignement itératif",
                    "Python",
                    "API REST",
                    "Networking",
                    "Bolidage",
                    "DevOps",
                    "Machine Learning",
                    "Coworking",
                    "IoT",
                    "Node.js",
                    "Low-Code",
                    "Android",
                    "iOS",
                    "TypeScript",
                    "Linux",
                    "Robotique",
                    "Congolexicomatisation",
                    "Machine Learning",
                    "IoT",
                    "Blockchain",
                ],
                autoStart: true,
                loop: true,
                deleteSpeed: 50,
            }}
        />
    );
}

export default Type;
