import React from "react";
import Typewriter from "typewriter-effect";

function Type() {
  return (
    <Typewriter
      options={{
          strings: [
              "Développeur",
              "Freelance",
              "Informatique",
              "Programmation",
              "Web",
              "Technologie",
              "Code",
              "Startup",
              "Application",
              "Innovation",
              "Numérique",
              "Cloud",
              "Software",
              "Mobile",
              "Full-Stack",
              "Back-End",
              "Front-End",
              "Développement",
              "Entrepreneuriat",
              "JavaScript",
              "Python",
              "React",
              "Node.js",
              "API",
              "Base de données",
              "SQL",
              "NoSQL",
              "DevOps",
              "Git",
              "GitHub",
              "Open Source",
              "SaaS",
              "Docker",
              "Kubernetes",
              "Agile",
              "Scrum",
              "UX/UI",
              "Design",
              "SEO",
              "Cloud Computing",
              "Machine Learning",
              "Intelligence Artificielle",
              "Big Data",
              "IoT",
              "Blockchain",
              "Smart Contracts",
              "Microservices",
              "Framework",
              "CMS",
              "WordPress",
              "Symfony",
              "Laravel",
              "Vue.js",
              "TypeScript",
              "Swift",
              "Kotlin",
              "Android",
              "iOS",
              "Responsive",
              "GraphQL",
              "REST",
              "API REST",
              "Firebase",
              "Testing",
              "CI/CD",
              "Automatisation",
              "Scripting",
              "Linux",
              "Cloud Native",
              "Edge Computing",
              "PenTesting",
              "Data Science",
              "Analyse de données",
              "Business Intelligence",
              "Freelancing",
              "Remote Work",
              "No-Code",
              "Low-Code",
              "E-commerce",
              "Web Scraping",
              "Growth Hacking",
              "Consultant",
              "Portfolio",
              "Coworking",
              "Networking",
              "Productivité",
              "Side Project",
              "API Gateway",
              "Serverless",
              "Web3",
              "Metaverse",
              "Robotique",
          ],
          autoStart: true,
        loop: true,
        deleteSpeed: 50,
      }}
    />
  );
}

export default Type;
